name: Run Tests

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo running tests
